from .cadepth.cadepth_predictor import CADepthPredictor
from .diffnet.diffnet_predictor import DIFFNetPredictor
from .adabins.adabins_predictor import AdaBinsPredictor
from .manydepth.manydepth_predictor import ManyDepthPredictor